import raw from "@/data/scene.json";

export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

interface SceneData {
  width: number;
  height: number;
  catSleep: Rect;
  catAwake: Rect;
  chair: Rect;
  lamp: Rect;
  binders: { shelf: number; index: number; file: string; rect: Rect; label: Rect; color: string }[];
  lavaBox: Rect;
  /** inside of the lava lamp glass, row by row: [x0, x1] relative to lavaBox */
  lavaRows: number[][];
  clock: { x: number; y: number; rx: number; ry: number };
  window: Rect;
  screen: Rect & { r: number };
  radio: Rect;
  lava: Rect;
  lampHit: Rect;
  bulb: { x: number; y: number };
  steam: Rect;
  mug: Rect;
  logo: { width: number; height: number; ball: { x: number; y: number; r: number } };
}

/** Geometry of the painted room, generated by scripts/build-scene.mjs (source pixels). */
export const SCENE = raw as unknown as SceneData;

export const sceneImg = (file: string) => `/scene/${file}`;

export const binderSlot = (slot: string) => {
  const [s, i] = slot.split("-").map(Number);
  return SCENE.binders.find((b) => b.shelf === s && b.index === i)!;
};
