import raw from "@/data/scene.json";

export interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}

interface SceneData {
  width: number;
  height: number;
  catSleep: Rect;
  catAwake: Rect;
  chair: Rect;
  lamp: Rect;
  binders: { shelf: number; index: number; file: string; rect: Rect; label: Rect; color: string }[];
  lavaBox: Rect;
  /** inside of the lava lamp glass, row by row: [x0, x1] relative to lavaBox */
  lavaRows: number[][];
  clock: { x: number; y: number; rx: number; ry: number };
  window: Rect;
  screen: Rect & { r: number };
  screenQuad: [number, number][];
  radio: Rect;
  lava: Rect;
  lampHit: Rect;
  bulb: { x: number; y: number };
  steam: Rect;
  mug: Rect;
  logo: { width: number; height: number; ball: { x: number; y: number; r: number } };
}

/** Geometry of the painted room, generated by scripts/build-scene.mjs (source pixels). */
export const SCENE = raw as unknown as SceneData;

export const sceneImg = (file: string) => `/scene/${file}`;

export const binderSlot = (slot: string) => {
  const [s, i] = slot.split("-").map(Number);
  return SCENE.binders.find((b) => b.shelf === s && b.index === i)!;
};

/**
 * CSS matrix3d that maps a w x h box (origin top-left) onto a quad
 * given as [TL, TR, BR, BL] (perspective / homography).
 */
export function quadMatrix(w: number, h: number, q: [number, number][]) {
  const [[x0, y0], [x1, y1], [x2, y2], [x3, y3]] = q;
  const dx1 = x1 - x2, dx2 = x3 - x2, dx3 = x0 - x1 + x2 - x3;
  const dy1 = y1 - y2, dy2 = y3 - y2, dy3 = y0 - y1 + y2 - y3;
  const den = dx1 * dy2 - dx2 * dy1;
  const g = (dx3 * dy2 - dx2 * dy3) / den;
  const hh = (dx1 * dy3 - dx3 * dy1) / den;
  const a = x1 - x0 + g * x1, b = x3 - x0 + hh * x3;
  const d = y1 - y0 + g * y1, e = y3 - y0 + hh * y3;
  const m = [a / w, d / w, 0, g / w, b / h, e / h, 0, hh / h, 0, 0, 1, 0, x0, y0, 0, 1];
  return `matrix3d(${m.map((v) => +v.toFixed(8)).join(",")})`;
}
